### PR TITLE
[now-cli] Render prompt when deploying home directory

### LINKED ISSUE #3069: Now should detect the home folder or warn users about the default behavior.
## Summary

It is very common that users run, by mistake, the `now` command in the home folder. This is especially common with new users and, even the deployment will likely fail, it can be a security issue for those users.

## Ideas

1. We can detect the home folder and avoid the command to exit successfully.
2. When deploying static files only, we can introduce a warning.
3. Detect the first run of the user and showcase the usage of the tool for the user. Something like a "video" tutorial but right in the terminal. We could ask the user to run the following steps:
 3.1 Would you like to run a tutorial y/n?
 3.2 If yes, then show a list of available examples and the user could select them.
 3.3 Explain what is happening and useful URLs.

### PR DESCRIPTION
**Pull request by thasophearak**
Fixes #3069 

PRODUCT-160 #close

### CODE REVIEW

**Review by AndyBitz — APPROVED** [review]

**Review by AndyBitz — CHANGES_REQUESTED** [review]
@sophearak I think we should add the same check to `legacy`

**Comment by thasophearak** [comment]
> I think we should add the same check to `legacy`

Ahh, you're right 👍

File: packages/now-cli/src/commands/deploy/legacy.ts [hunk 1]
```diff
@@ -269,6 +270,17 @@ export default async function main(
     paths = [process.cwd()];
   }
 
+  if (argv._[0] === homedir()) {
```
Comment (styfle) [inline packages/now-cli/src/commands/deploy/legacy.ts]: Consider turning this into a function so it can be used in both v1 and v2:

```ts
async function shouldDeployDir(argv0, output) {
  let yes = true;
  if (argv0 === homedir()) {
    yes = await promptBool('You are deploying your home directory. Do you want to continue?');
    if (!yes) {
      output.log('Aborted');
    }
  }
  return yes;
}

// then the only repeated code you need is the following:
if (!(await shouldDeployDir(argv._[0], output))) {
  return 0;
}
```

Comment (thasophearak) [reply packages/now-cli/src/commands/deploy/legacy.ts]: will do 🙌

**Review by AndyBitz — CHANGES_REQUESTED** [review]
`should-deploy-dir.js` should be typescript

File: packages/now-cli/src/commands/deploy/legacy.ts [hunk 2]
```diff
@@ -40,6 +40,8 @@ import formatLogOutput from '../../util/output/format-log-output';
 // @ts-ignore
 import getEventsStream from '../../util/deploy/get-events-stream';
 // @ts-ignore
```
Comment (AndyBitz) [inline packages/now-cli/src/commands/deploy/legacy.ts]: `@ts-ignore` is not necessary anymore

**Review by AndyBitz — CHANGES_REQUESTED** [review]

**Review by AndyBitz — APPROVED** [review]
