### PR TITLE
[now-cli][now-client] Add parameter `nowConfig` for custom now.json

### LINKED ISSUE #3099: Latest `now@16.3.0` broke `--local-config`
Hi!

Maybe someone already posted this but the last version of `now` broke deployments.

It searching for a `build` in `package.json` but I think it's confusing the `package.json` from the workspace and doesn't think about the `package.json` for the actual builder.

```
> Error! Your `package.json` file is missing a `build` property inside the `script` property.
More details: https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-build-script
error Command failed with exit code 1.
```

I use a `json` file for `now --local-config` who specify the correct package. I didn't made a deployment since last week. And yes, there is a `build` into the `package.json` of the package. 

Everything were working perfectly fine during the last few months (even my last deployment last week), since this morning it's impossible with the latest version of `now`.

I just updated this morning and now it's impossible to deploy. Even simple simples boilerplates from github. :/ 

Hope you'll fix it soon!

Thx a lot for everything 😄 

EDIT:
Right now, I've downgrade to the 16.2.0 version to be able to deploy
I've tested the 16.3.0 and there definitely an issue there :) 
Good luck to the team to fix it!

### LINKED ISSUE #3105: [now-cli] upgrading to 16.3.0 breaks the routes
**Summary**

I'm hosting a `static build` of my CRA bootstrapped app to Zeit. After upgrading to 16.3.0, my route redirection to root file stopped working. I was using `now.json.routes` to redirect all my dynamic routes to `index.html` file for frontend route handling. I am getting 404 errors while accessing routes other than index. Reverting back to **16.2.0** seams to fix this issue.

My `now.json` file
```json
{
  "name": "app-name",
  "routes": [
    { "src": "/static/(.*)", "dest": "/static/$1" },
    { "src": "/(.*\\.(js|json|png|jpg|ico|txt))", "dest": "/$1" },
    { "src": "/(.*)", "dest": "/" }
  ]
}
```

**Steps to reproduce**

Any `SPA` which is statically hosted with above `routes` configuration should reproduce the issue when deployed with `now-cli@16.3.0`.

### LINKED ISSUE #3107: [now-cli] Now cli 16.3.0 `--prod` option does not alias domain when build succeeded
Hi everyone,

First of all, amazing service and this is really the first time I've found an issue in a process that was overall very seamless, thank you!

Now I did get an issue with updating `now-cli` to 16.3.0, and to my surprise my build does not get to be aliased to my custom domain. Going back to `now-cli@16.2.0` fixes my issue completely.

My command is the following:
```
now --prod --local-config ./.now/now.dev.json
```
My config is:
```
{
  "name": "website-dev",
  "alias": "domain.com",
  "version": 2,
  "build": {
    "env": {
      // hidden
    }
  },
  "builds": [{
    "src": "next.config.js",
    "use": "@now/next"
  }]
}
```

Is there something I need to update to support the newer now-cli updates?

Thanks in advance, let me know if you need more info from me!

### LINKED ISSUE #3109: Now + Next.js: "Please install typescript" error with --prod deployment
I have a staging/production environment on Zeit for a frontend application done in Next.js.
Last prod deployment was done 4 days ago, without issues.

Today I've merged staging into prod, but I get an error that blocks the deployment while building the application:
```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Please install typescript by running:
         npm install --save-dev typescript
If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files)
```
I'm not sure what is the reason why this error shows up now and not in the previous builds. I've checked the builds logs and nothing changed.

I could probably solve this by adding typescript as **prod dependency** instead of having it as devDependency in my package.json file, but I'm not sure why the error is happening now and wasn't there on the latest releases.

Another workaround would be to not use the **--prod flag** on the **production deployment** since the issue doesn't happen with the **staging deployment** that doesn't use the --prod flag.

This is the full deployment command I'm using
```
now --prod --token $ZEIT_TOKEN --local-config .now/now.production.json
```

I have a gut feeling that it might be connected to #3107 and #3105 

Any hints?

Ps: I've also open a [thread on spectrum](https://spectrum.chat/zeit/general/now-next-js-please-install-typescript-error-on-production-deployment~6cc5a743-0ca1-4e21-b45f-02a8ee0dcfb8) and seems I'm not the only one

### PR DESCRIPTION
**Pull request by styfle**
When now-client was implemented, it did not work with `--local-config` flag from now-cli because the only parameters it looks at are the files in a directory.

This fixes the regression in now@16.3.0 so that now-client can accept an optional `nowConfig` object or fallback to the `now.json` file.

Fixes #3099 
Fixes #3105
Fixes #3107
Fixes #3109

[PRODUCT-350] #close

[PRODUCT-350]: https://zeit.atlassian.net/browse/PRODUCT-350

### CODE REVIEW

File: packages/now-cli/src/util/deploy/process-deployment.ts [hunk 1]
```diff
@@ -20,18 +24,34 @@ export default async function processDeployment({
...
+  legacy: boolean,
+  env: any,
+  quiet: boolean,
+  nowConfig?: NowConfig
+}) {
+  const { warn, log, debug } = output;
   let bar: Progress | null = null;
 
+  const path0 = paths[0];
+  const opts = {
```
Comment (TooTallNate) [inline packages/now-cli/src/util/deploy/process-deployment.ts]:
```suggestion
  const opts: DeploymentOptions = {
```

File: packages/now-client/src/deploy.ts [hunk 2]
```diff
@@ -231,3 +233,5 @@ export default async function* deploy(
     }
   }
 }
+
```
Comment (TooTallNate) [inline packages/now-client/src/deploy.ts:236]: Weird spacing? Maybe run `prettier` on this file

**Review by TooTallNate — APPROVED** [review]

File: packages/now-client/src/deploy.ts (hunk 2 above)
Comment (styfle) [reply packages/now-client/src/deploy.ts:236]: Done ✅
