### PR TITLE
[now update] Add message saying that Windows is not supported

### LINKED ISSUE #2492: now cli update throwing EBUSY error
```
$ now update
> UPDATE AVAILABLE The latest version of Now CLI is 15.6.2
> Run the `now update` command to update to the latest version
> Changelog: https://github.com/zeit/now-cli/releases/tag/15.6.2
> Now CLI 15.5.0 update (beta) — https://zeit.co/feedback/update
> Updating Now CLI...

  Configuration

    platform    win
    arch        x64
    location    C:\Users\reach\AppData\Roaming\npm\node_modules\now\download\dist\now.exe
    version     15.6.2 (latest stable release)

> Downloading `now` binary...
> Binary URL: https://github.com/zeit/now-cli/releases/download/15.6.2/now-win.exe.gz
> Update Now CLI? [y/N] y
> Error! An unexpected error occurred in update: Error: EBUSY: resource busy or locked, open 'C:\Users\reach\AppData\Roaming\npm\node_modules\now\download\dist\now.exe'
    at WriteStream.t.error.t (C:\snapshot\repo\dist\index.js:1:1589155)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.EventEmitter.emit (domain.js:442:20)
    at C:\snapshot\repo\dist\index.js:1:2874894
    at C:\snapshot\repo\dist\index.js:1:2875329
    at FSReqWrap.oncomplete (fs.js:171:20)
```

### PR DESCRIPTION
**Pull request by TooTallNate**
And direct the user back to the download page in order to re-install.

Closes #2492.

### CODE REVIEW

File: src/commands/update.ts [hunk 1]
```diff
@@ -208,6 +208,12 @@ export default async function main(ctx: NowContext): Promise<number> {
   const output = createOutput({ debug: debugEnabled });
   const { log, error, note, success, print, debug } = output;
 
+  if (isWin) {
+    error('The `now update` command is not supported on Windows.');
+    log(`To get the latest version, please re-install Now CLI: ${chalk.cyan.underline('https://zeit.co/download')}`);
+    return 0;
```
Comment (styfle) [inline src/commands/update.ts]: Should this be `return 1` since its an error?

```suggestion
    return 1;
```

**Review by styfle — APPROVED** [review]
