### PR TITLE
[cli] Fix dev query string merging

### LINKED ISSUE #7283: [CLI] When "vercel dev" proxies a request to a framework, its queries are not original ones and will result in errors for Vite.
When Vite plugins processing a Vue Single File Component(SFC) file, it will transform its style tag into a js file with a url like 
`/foo/bar/AComponent.vue?vue&type=style&index=0&lang.css`. Then it was used as a js module in the page.

However when Vercel CLI dev server proxying it to frontend dev server, the cli doesn't use original url but generates a new one.
Generated one is like: `/foo/bar/AComponent.vue?vue=&type=style&index=0&lang.css=`, which is not a valid css url that can be recognized by Vite. Its content is not processed by css plugins of Vite, but it's still used as a js module.

Because of that, when running "vercel dev", if you write some css rules in the style tag of a Vue SFC file, the page will become blank and throw errors in browser console. It's very inconvenient for Vue developers if we can't use style tag in SFC.

Cause is at: 
https://github.com/vercel/vercel/blob/bae26cc0178ff49c3050ceaf5db00969e510cc6b/packages/cli/src/util/dev/server.ts#L1703-L1707

Here it deletes original querystring (`origUrl.search`), and generates a new one together with pathname (`url.format(origUrl)`), which is the one with additional "=". (`url.format()` internally uses `querystring.stringify()` that will add "=" for empty fields in the object).

In my local repo, I deleted L1704 & L1706 then it worked as expected. `url.format()` now uses original search string, so additional "="s are gone. But I don't know if it will impact other frameworks.

### PR DESCRIPTION
**Pull request by styfle**
Since `vercel dev` performs query string merging with `vercel.json` routes and the requested url, there is sometimes a slight difference between the request that the browser sends and the request that the upstream dev server receives.

Most servers treat the query string key with "empty" value the same as undefined value. Meaning, these two URLs should be equivalent because each has empty values:

- `http://example.com/src/App.vue?vue&type=style&index=0&lang.css`
- `http://example.com/src/App.vue?vue=&type=style&index=0&lang.css=`

However, `vite dev` handles these two URLs differently because of [string comparisons](https://github.com/vitejs/vite/blob/2289d04af5398791c3a01c9e597dc976e593c852/packages/plugin-vue/src/handleHotUpdate.ts#L98-L99) instead of URL parsing, which causes requests from `vercel dev` to fail. Thus, this PR changes from Node.js native URL parsing to a custom implementation in order to handle this corner case and preserve the difference between `?a=` and `?a`.

Ideally this would be [fixed in vite](https://github.com/vitejs/vite/pull/9589), however we might run into other dev servers that also fail in the same way in the future.

- Fixes https://github.com/vercel/vercel/issues/7283
- Closes https://github.com/vitejs/vite/pull/9589
- Related to https://github.com/nodejs/node/issues/9500

### CODE REVIEW

**Comment by micahlt** [comment]
What's the status of this?  It'd be great to have this merged.

**Comment by styfle** [comment]
The tests are failing and there are merge conflicts. 

It might be faster to [submit a PR to Vite](https://github.com/vitejs/vite/pull/9589) to fix this since it’s the only framework that has an issue.

File: packages/cli/src/util/dev/parse-query-string.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  for (let param of params) {
+    const [key, value] = param.split('=');
+
+    let existing = map.get(key);
+    if (!existing) {
+      existing = [];
+      map.set(key, existing);
+    }
+
+    existing.push(value);
```
Comment (cb1kenobi) [inline packages/cli/src/util/dev/parse-query-string.ts:29]: Do you need to `decodeURIComponent()` the value?

Comment (TooTallNate) [reply packages/cli/src/util/dev/parse-query-string.ts:29]: Ya I believe we need to decode both the key and value.

Comment (styfle) [reply packages/cli/src/util/dev/parse-query-string.ts:29]: Just to be clear, are suggesting decoding during parse() and encoding during format()?

Comment (cb1kenobi) [reply packages/cli/src/util/dev/parse-query-string.ts:29]: I only tested the parse, but you should probably also `encodeURIComponent()` during format.

Comment (styfle) [reply packages/cli/src/util/dev/parse-query-string.ts:29]: I updated in [a5aee22](https://github.com/vercel/vercel/pull/8183/commits/a5aee2278269a19d2974e3888330bb720ff3ee01) so this behavior matches `url.parse()` and `url.format()` with decode and encode respectively. Nice catch! 👍

File: packages/cli/src/util/dev/parse-query-string.ts [hunk 2]
```diff
@@ -0,0 +1,47 @@
+export function parseQueryString(querystring?: string) {
+  let map = new Map<string, string[]>();
```
Comment (Ethan-Arrowood) [inline packages/cli/src/util/dev/parse-query-string.ts]: nit: prefer const

```suggestion
  const map = new Map<string, string[]>();
```

File: packages/cli/test/unit/util/dev/parse-query-string.test.ts [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    const parsed = parseQueryString(querystring);
+    const map = new Map<string, string[]>([
+      ['a', []],
+      ['b', ['1']],
+      ['c', ['2', '3']],
+      ['d', ['']],
+      ['space bar', ['4']],
+      ['html', ['<h1>']],
+    ]);
+    expect(parsed).toEqual(map);
```
Comment (Ethan-Arrowood) [inline packages/cli/test/unit/util/dev/parse-query-string.test.ts]: should these be strict/deep equals?

**Review by Ethan-Arrowood — APPROVED** [review]
lgtm, just one code nit and then a question about the assertions used in the tests

File: packages/cli/test/unit/util/dev/parse-query-string.test.ts (hunk 3 above)
Comment (styfle) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: This is jest which is deep equal already https://jestjs.io/docs/expect#toequalvalue

If it wasn't deep equal it would fail because its comparing different references 🙂

File: packages/cli/src/util/dev/parse-query-string.ts (hunk 2 above)
Comment (styfle) [reply packages/cli/src/util/dev/parse-query-string.ts]: Fixed in [2d36b10](https://github.com/vercel/vercel/pull/8183/commits/2d36b101432ad91b96128c33547568c3fc1c8d0a). I guess we should update to https://github.com/vercel/style-guide 🙂

File: packages/cli/test/unit/util/dev/parse-query-string.test.ts [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+    const format = formatQueryString(parsed);
+    expect(format).toEqual(undefined);
+  });
+  it('should work with question mark', async () => {
+    const parsed = parseQueryString('?');
+    expect(parsed).toEqual(new Map());
+    const format = formatQueryString(parsed);
+    expect(format).toEqual(undefined);
+  });
+  it('should work without question mark', async () => {
```
Comment (TooTallNate) [inline packages/cli/test/unit/util/dev/parse-query-string.test.ts:34]: What is this case for?

File: packages/cli/test/unit/util/dev/parse-query-string.test.ts [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+  parseQueryString,
+  formatQueryString,
+} from '../../../../src/util/dev/parse-query-string';
+
+describe('parseQueryString', () => {
+  it('should parse to Map and format back to original String', async () => {
+    const querystring = '?a&b=1&c=2&c=3&d=&space%20bar=4&html=%3Ch1%3E';
+    const parsed = parseQueryString(querystring);
+    const map = new Map<string, string[]>([
+      ['a', []],
```
Comment (TooTallNate) [inline packages/cli/test/unit/util/dev/parse-query-string.test.ts]: I thought this case would have `[undefined]` as the value here? What if we're parsing `?a&a&a&a&a=1`?

Comment (TooTallNate) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: I also wonder if Map is even really the correct data structure here. How do we retain ordering when formatting again? i.e. `parse('?a=1&b=2&a=3'`)? I think the current code would format _both_ `a` values before the `b` value.

File: packages/cli/test/unit/util/dev/parse-query-string.test.ts (hunk 4 above)
Comment (styfle) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts:34]: These are just unit tests so I wanted to have full coverage. I don't think this is actually possible when passing the result of `url.parse(foo).search` into this function.

File: packages/cli/test/unit/util/dev/parse-query-string.test.ts (hunk 5 above)
Comment (cb1kenobi) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: That's a good question. I have used `Map` many times, but never with the intent of preserving key order, which I know `Object` does. Silly question, why not just use `URLSearchParams`?

Comment (styfle) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: > The Map object holds key-value pairs and remembers the original insertion order of the keys. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Comment (styfle) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: Although I think you might be right about the duplicate keys that are undefined. Let me add a test for that 👀

Comment (TooTallNate) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: The point about Map insertion order doesn't really address the issue though. My example had `a,b,a` and right now the code will format back to `a,a,b`.

Comment (cb1kenobi) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: FYI, `URLSearchParams` allows for duplicate keys:

```
> const u = new URLSearchParams('?a=1&b=2&a=3');
undefined
> u
URLSearchParams { 'a' => '1', 'b' => '2', 'a' => '3' }
> u.entries()
URLSearchParams Iterator { [ 'a', '1' ], [ 'b', '2' ], [ 'a', '3' ] }
```

It also supports with or without the `?` and empty values:

```
> new URLSearchParams('a=&b=&a')
URLSearchParams { 'a' => '', 'b' => '', 'a' => '' }
```

Comment (styfle) [reply packages/cli/test/unit/util/dev/parse-query-string.test.ts]: @cb1kenobi Unfortunetly this suffers from the same bug:

```
> new URLSearchParams('a=&b=&a')
URLSearchParams { 'a' => '', 'b' => '', 'a' => '' }
```

Because we need the first `a` to be empty string and the second `a` to be undefined. Otherwise we can't tell which one had an equals sign (see PR description).

I switched the code back to a plain Object so that its compatible with the existing `url.parse()` and `url.format()` API. 

I think the order of `a,b,a` to `a,a,b` will need to be fixed in a future PR since that is out of scope for the `vite dev` fix and that is the issue customers are blocked on.

**Review by EndangeredMassa — APPROVED** [review]

**Review by TooTallNate — APPROVED** [review]

File: packages/cli/src/util/dev/parse-query-string.ts [hunk 6]
```diff
@@ -0,0 +1,59 @@
+/**
```
Comment (cb1kenobi) [inline packages/cli/src/util/dev/parse-query-string.ts:1]: Since this implementation does not preserve the order of the params, and assuming we care, perhaps there should be a TODO stating the limitation.

File: packages/cli/src/util/dev/router.ts [hunk 7]
```diff
@@ -56,7 +57,8 @@ export async function devRouter(
   phase?: HandleValue | null
 ): Promise<RouteResult> {
   let result: RouteResult | undefined;
-  let { query, pathname: reqPathname = '/' } = url.parse(reqUrl, true);
+  let { pathname: reqPathname = '/', search: reqSearch } = url.parse(reqUrl);
```
Comment (cb1kenobi) [inline packages/cli/src/util/dev/router.ts:60]: With `url.parse()` having been deprecated, perhaps we should switch to the new, futureproof method:

```javascript
let { pathname: reqPathname = '/', search: reqSearch } = new URL(reqUrl);
```

Note that the URL must have a protocol and domain, otherwise the call would look like `new URL(reqUrl, 'http://localhost')`.

**Comment by micahlt** [comment]
🎉 Thank you so much for your hard work on this @styfle!

File: packages/cli/src/util/dev/router.ts (hunk 7 above)
Comment (styfle) [reply packages/cli/src/util/dev/router.ts:60]: Its not really deprecated https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost

image

Comment (cb1kenobi) [reply packages/cli/src/util/dev/router.ts:60]: Ha, revoked!
