### PR TITLE
[cli][client] Handle `--repo` linked in `vc deploy --prebuilt`

### LINKED ISSUE #11097: vercel@33.3.0 broke preBuilds in monorepo
We are using the `preBuild` option in our monorepo but after updating to vercel@33.3.0 it no longer works, when trying to do the deploy we get the following error:
```
[debug] [2024-01-26T09:52:00.561Z] Error: Error: ENOENT: no such file or directory, lstat '/home/runner/work/<org>/<project>/dist/apps/<app-name>/node_modules/styled-jsx/index.js'

Error: ENOENT: no such file or directory, lstat '/home/runner/work/<org>/<project>/dist/apps/<app-name>/node_modules/styled-jsx/index.js'
```

When comparing it with the previous version it looks like the functions don't have the node_modules anymore. How can we solve this?

### PR DESCRIPTION
**Pull request by TooTallNate**
`vc deploy --prebuilt` has not properly worked for projects linked with `vc link --repo` ever since https://github.com/vercel/vercel/issues/11077.

To fix, don't mutate `cwd` to be the project subdir (so that `cwd` is always the monorepo root), and instead pass in a new property to `@vercel/client` that represents the `.vercel/output` file path. A lot of the code is just passing this new variable through the multiple layers of indirection in CLI before it finally reaches `@vercel/client.

Fixes https://github.com/vercel/vercel/issues/11097.

### CODE REVIEW

File: packages/client/src/utils/index.ts [hunk 1]
```diff
@@ -148,20 +149,27 @@ export async function buildFileTree(
...
+    if (typeof vercelOutputDir !== 'string') {
+      throw new Error(`Missing required \`vercelOutputDir\` parameter`);
+    }
+    if (typeof cwd !== 'string') {
+      throw new Error(`\`cwd\` must be a "string"`);
+    }
+    const relOutputDir = relative(cwd, vercelOutputDir);
     ignores = ['*'];
-    const parts = outputDir.split('/');
+    const parts = relOutputDir.split(sep);
```
Comment (erikareads) [inline packages/client/src/utils/index.ts:169]: Why does this use `sep` when the next two calls use raw `'/'`?

File: packages/client/src/utils/index.ts [hunk 2]
```diff
@@ -148,20 +149,27 @@ export async function buildFileTree(
...
     parts.forEach((_, i) => {
       const level = parts.slice(0, i + 1).join('/');
       ignores.push(`!${level}`);
     });
-    ignores.push(`!${outputDir}/**`);
+    ignores.push(`!${parts.join('/')}/**`);
```
Comment (erikareads) [inline packages/client/src/utils/index.ts:174]: Is there a path aware join that we could use here instead of the array join?

File: packages/client/src/utils/index.ts (hunk 1 above)
Comment (TooTallNate) [reply packages/client/src/utils/index.ts:169]: For this (and your next comment), it's because the input is (potentially) a Windows path (with `\`), but the `ignore` module expects Unix paths

File: packages/client/src/utils/index.ts [hunk 3]
```diff
@@ -148,20 +149,27 @@ export async function buildFileTree(
...
+  prebuilt?: boolean,
+  vercelOutputDir?: string
 ): Promise<{ ig: Ignore; ignores: string[] }> {
   const ig = ignore();
   let ignores: string[];
 
   if (prebuilt) {
-    const outputDir = '.vercel/output';
+    if (typeof vercelOutputDir !== 'string') {
+      throw new Error(`Missing required \`vercelOutputDir\` parameter`);
```
Comment (EndangeredMassa) [inline packages/client/src/utils/index.ts]:
```suggestion
      throw new Error(`Missing required \`vercelOutputDir\` parameter when "prebuilt" is true);
```

**Review by EndangeredMassa — DISMISSED** [review]
I manually tested this and it worked for me in a monorepo that was `--repo` linked

**Comment by EndangeredMassa** [comment]
updated to include the CI fix from main

**Review by EndangeredMassa — APPROVED** [review]
