### PR TITLE
[now-client] Fix windows paths handling

### LINKED ISSUE #2972: `createDeployment()` is broken on Windows
On Windows, `now-client`'s `createDeployment()` function does not properly handle Windows slashes. So it ends up sending full file paths to the API, rather than paths relative to the upload directory and with normalized Unix slashes. This results in all files being visible from the top-level and improperly named, including the full file path from the user's machine.

Example deployment (created from Now CLI canary after #2875 was merged): https://my-angular-app-fqbgv6pjl.n8.io/

### PR DESCRIPTION
**Pull request by rdev**
This PR ensures Windows path separators are handled properly (fixes #2972)

### CODE REVIEW

File: packages/now-client/src/utils/index.ts [hunk 1]
```diff
@@ -143,17 +145,19 @@ export const prepareFiles = (
...
         if (options.isDirectory) {
           // Directory
-          fileName = options.path ? name.replace(`${options.path}/`, '') : name;
+          fileName = options.path
+            ? name.replace(isWin ? `${options.path}\\` : `${options.path}/`, '')
+            : name;
         } else {
           // Array of files or single file
-          const segments = name.split('/');
+          const segments = isWin ? name.split('\\') : name.split('/');
```
Comment (AndyBitz) [inline packages/now-client/src/utils/index.ts]: Maybe we should use `path.sep` instead?

Comment (styfle) [reply packages/now-client/src/utils/index.ts]: Agreed. Use this:

```suggestion
          const segments = name.split(path.sep);
```

File: packages/now-client/src/utils/index.ts [hunk 2]
```diff
@@ -143,17 +145,19 @@ export const prepareFiles = (
...
           fileName = segments[segments.length - 1];
         }
 
         next.push({
-          file: fileName,
+          file: fileName.replace(/\\/g, '/'),
```
Comment (styfle) [inline packages/now-client/src/utils/index.ts]: I'm not sure if we already have a normalizePath() function but we could probably add a common function since there are several packages that need this behavior (doesn't have to be in this PR).

File: packages/now-client/src/utils/index.ts [hunk 3]
```diff
@@ -143,17 +145,19 @@ export const prepareFiles = (
 
         if (options.isDirectory) {
           // Directory
-          fileName = options.path ? name.replace(`${options.path}/`, '') : name;
+          fileName = options.path
+            ? name.replace(isWin ? `${options.path}\\` : `${options.path}/`, '')
```
Comment (TooTallNate) [inline packages/now-client/src/utils/index.ts]:
```suggestion
            ? name.substring(options.path.length + 1)
```

File: packages/now-client/src/utils/index.ts (hunk 2 above)
Comment (TooTallNate) [reply packages/now-client/src/utils/index.ts]: I think this normalization should only happen on Windows. In Unix, it's technically possible to have backslashes in a filename.

```
$ touch 'foo\bar'
$ ls -l foo\\bar 
-rw-r--r-- 1 nrajlich staff 0 Sep  6 14:28 'foo\bar'
```

File: packages/now-client/src/utils/index.ts (hunk 1 above)
Comment (rdev) [reply packages/now-client/src/utils/index.ts]: TIL
Will do 👍🏻

**Review by AndyBitz — APPROVED** [review]
