### PR TITLE
[now-cli] Handle `now certs ls` for users and teams without certificates

### LINKED ISSUE #2944: Broken `now certs ls`
As you can see here, the command doesn't work at all:

image

Might be related to https://github.com/zeit/now/issues/2786.

### PR DESCRIPTION
**Pull request by AndyBitz**
This makes sure that [this error](https://sentry.io/organizations/zeithq/issues/1203843024/?referrer=slack) will be handled.

It further adds tests and moves all \`certs\` commands to typescript.

Fixes https://github.com/zeit/now/issues/2944

### CODE REVIEW

File: packages/now-cli/src/commands/certs/add.ts [hunk 1]
```diff
@@ -107,34 +126,43 @@ async function add(ctx, opts, args, output) {
     }
 
     // Create the certificate from the given array of CNs
-    const cns = args.reduce((res, item) => [...res, ...item.split(',')], []);
+    const cns = args.reduce<string[]>((res, item) => res.concat(...item.split(',')), []);
```
Comment (nkzawa) [inline packages/now-cli/src/commands/certs/add.ts]: I was not sure if it's intended.

```suggestion
    const cns = args.reduce<string[]>((res, item) => res.concat(item.split(',')), []);
```

File: packages/now-cli/src/commands/certs/ls.ts [hunk 2]
```diff
@@ -113,26 +122,26 @@ function formatCert(time, cert) {
...
 
-function formatCertFirstCn(time, cert, cn, multiple) {
+function formatCertFirstCn(time: Date, cert: Cert, cn: string, multiple: boolean): string[] {
   return [
     cert.uid,
     formatCertCn(cn, multiple),
     formatExpirationDate(new Date(cert.expiration)),
     cert.autoRenew ? 'yes' : 'no',
-    chalk.gray(ms(time - new Date(cert.created)))
+    chalk.gray(ms(time.getTime() - new Date(cert.created).getTime()))
```
Comment (nkzawa) [inline packages/now-cli/src/commands/certs/ls.ts:139]: 👍

**Review by nkzawa — APPROVED** [review]
