### PR TITLE
[remix] Ignore `serverBuildPath` from Remix config

### LINKED ISSUE #9524: Error: File /vercel/path0/api/index.js does not exist
**Vercel deployment for remix is not working after the latest update.**

No build errors but throwing error while deployment - `Error: File /vercel/path0/api/index.js does not exist.`
Tried deploying a new branch or redeployed already built branch, failed with the above error. This happened after today's latest update.

image

### PR DESCRIPTION
**Pull request by TooTallNate**
We are explicitly overriding `serverBuildPath` so there is no need to use the value that `readConfig()` gives to us.

Fixes #9524.

### CODE REVIEW

File: packages/remix/src/build.ts [hunk 1]
```diff
@@ -167,17 +168,13 @@ module.exports = config;`;
         });
       }
     }
-    remixConfig = await chdirAndReadConfig(entrypointFsDirname);
```
Comment (TooTallNate) [inline packages/remix/src/build.ts:170]: This second read `readConfig()` call was not actually doing anything, since `readConfig()` uses `await import()` and thus the module was cached and didn't pick up our patches.

File: packages/remix/test/fixtures/02-remix-basics-mjs/remix.config.mjs [hunk 2]
```diff
@@ -3,6 +3,7 @@
  */
 export default {
   ignoredRouteFiles: ["**/.*"],
+  serverBuildTarget: "vercel",
```
Comment (cb1kenobi) [inline packages/remix/test/fixtures/02-remix-basics-mjs/remix.config.mjs:6]: Admittedly I'm a bit out-of-the-loop, but Remix docs say `serverBuildTarget` has been deprecated. Is this line just testing that `config.serverBuildTarget = undefined;` scrubs the config value?

Comment (TooTallNate) [reply packages/remix/test/fixtures/02-remix-basics-mjs/remix.config.mjs:6]: It is deprecated, but still exists in projects out in the wild. This PR is basically for backwards compat.

**Review by cb1kenobi — APPROVED** [review]

**Review by Ethan-Arrowood — APPROVED** [review]

**Review by styfle — APPROVED** [review]
