### PR TITLE
[now-next] Include file mode for pseudo layers

### LINKED ISSUE #3503: Now and Next.js don't work with spawning an executable
If you build a Next.js application, which spawns a process in a Next api page, it seems like either Next.js or Now is not correctly copying over the executable file to be spawned. Concretely, it's not keeping the executable access permission (which can be obtained with `chmod +x filename`.

The resulting error is
`Error: spawn /var/task/node_modules/dummy-executable-package/executable EACCES`

This issue blocks the usage of Photon.js together with Next.js deployed to Now. 
It's tracked here: https://github.com/prisma/prisma2/issues/1170

I created a minimal reproduction without Photon.js and just a simple package spawning a Node.js shebang executable here: https://github.com/timsuchanek/p2-1170

This is the example package including the executable: https://github.com/timsuchanek/dummy-executable-package

### PR DESCRIPTION
**Pull request by AndyBitz**
fixes #3503 

The executable permission is missing when adding the `node_modules` folder to the lambda zip, which caused errors when executing a file from inside.

### CODE REVIEW

**Review by Timer — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

File: packages/now-next/src/utils.ts [hunk 1]
```diff
@@ -501,15 +502,17 @@ export async function createPseudoLayer(files: {
         file,
         isSymlink: true,
         symlinkTarget: await fs.readlink(file.fsPath),
```
Comment (styfle) [inline packages/now-next/src/utils.ts:504]: I think you're missing the `mode` here 🤔
