### PR TITLE
[now-client] Fix file permissions for source files

### LINKED ISSUE #3172: File permissions are not preserved with now@16.3.0 and up
I using the following config to upload a executable file in my `now.json`:
```json
  "builds": [
    {
      "src": "index.go",
      "use": "@now/go",
      "config": {
        "includeFiles": [
          "domain/files/myExec"
        ]
      }
    }]
```
..and using it with this code:
```go
cmd := exec.Command("./domain/files/myExec")
err := cmd.Run()
```

This worked fine with `16.2.0`.
Today I updated to `16.3.1` (and also testet `16.3.0` - same issue) and for some reasons I get this error:
> Error: fork/exec ./domain/files/myExec: permission denied ()

From my naiv point of view it looks like that the permission of that file aren't set in 16.3.+ anymore.
But could be also totally wrong 😂 

For now I will stick at `16.2.0`. So not a very important fix required for me  but maybe for others.

### PR DESCRIPTION
**Pull request by styfle**
There was a regression since 16.3.0 (now-client refactor) causing file permissions for source files to be not be preserved.

The solution was to add the FS `mode` to each file.

Fixes #3172

### CODE REVIEW

File: packages/now-client/src/utils/hashes.ts [hunk 1]
```diff
@@ -42,22 +43,23 @@ export const mapToObject = (
...
-  const map = new Map();
+  const map = new Map<string, DeploymentFile>();
   const semaphore = new Sema(100);
 
   await Promise.all(
     files.map(
       async (name: string): Promise<void> => {
         await semaphore.acquire();
         const data = await fs.readFile(name);
+        const { mode } = await fs.stat(name);
```
Comment (TooTallNate) [inline packages/now-client/src/utils/hashes.ts:54]: Should this be `lstat()` instead? I'm not sure if we support symlinks in file uploads…

Comment (styfle) [reply packages/now-client/src/utils/hashes.ts:54]: I think `fs.readFile` is going to follow the symlink so there would need to be a change there too, right?

Comment (TooTallNate) [reply packages/now-client/src/utils/hashes.ts:54]: Ya, proper symlink support requires some API changes it seems. Using `fs.stat()` here in this case is correct.

**Review by TooTallNate — APPROVED** [review]
