### PR TITLE
[now dev] Fix @now/static-build sorting

### LINKED ISSUE #2323: [now dev] order in now.json builds array makes lambdas unreachable
The problem is that if I generate a new gatsby project from the now-cli and add a lambda, if i add the lambda builder after the static builder in `now.json` when i go to the url for the lambda i get the gatsby 404 page.

### repo to reproduce

https://github.com/jb-san/now-dev-lambda-routes

`now -v` 15.2.0

if you change the order of the builds in `now.json` so that the `@now/node` build is first, it works as expected
run it with `now dev`

### PR DESCRIPTION
**Pull request by AndyBitz**
Fix @now/static-build sorting, since it overwrites the routes of other builders. This also adds a test for this.

Fixes https://github.com/zeit/now-cli/issues/2323.

### CODE REVIEW

File: src/util/dev/server.ts [hunk 1]
```diff
@@ -388,6 +388,22 @@ export default class DevServer {
       }
     }
 
+    if (Array.isArray(config.builds)) {
+      // `@now/static-build` needs to be the last builder
+      // since it might catch all other requests
+      config.builds = config.builds.sort((buildA, buildB) => {
```
Comment (TooTallNate) [inline src/util/dev/server.ts]: `Array#sort()` modifies the array in-place, so no need to re-assign.

```suggestion
      config.builds.sort((buildA, buildB) => {
```

File: test/dev-server.unit.js [hunk 2]
```diff
@@ -200,3 +200,14 @@ test(
     }
   })
 );
+
+test(
+  '[DevServer] Test @now/static-build routing',
+  testFixture('now-dev-static-build-routing', async (t, server) => {
+    {
+      const res = await fetch(`${server.address}/api/date`);
```
Comment (TooTallNate) [inline test/dev-server.unit.js:208]: Since this fixture has a `now.json` file (so not zero-config), the URL needs to have the .js suffix.

```suggestion
      const res = await fetch(`${server.address}/api/date.js`);
```

Comment (AndyBitz) [reply test/dev-server.unit.js:208]: @TooTallNate I've added a route to the test

 ```
  "routes": [
    { "src": "^/api/date$", "dest": "api/date.js" }
  ]
```

**Review by TooTallNate — APPROVED** [review]
