### PR TITLE
[now update] Show correct global or local install command

### LINKED ISSUE #2683: Provide helpful message for new users and fix local installation messages
For new users that don't have correct permissions set and want to install Now CLI, we want to provide a really good error message:

```
Error! ZEIT Now failed to place `now` in a directory in your executable path ($PATH).

To solve it, you have two options.

Option A)

Run this command to adjust permissions of the npm global directory and re-install `now`:

> sudo chown $(whoami) /usr/local/{bin,lib/node_modules} && npm i -g now@canary

Option B)

Follow this npm guide to create a different directory into which you can install `now` and
add it to your $PATH

> url to npm guide
```

These are the necessary items in total:

- [x] 1. Test local installation (and make sure the update message looks correct)
- [x] 2. Implement the message shared above
- [x] 3. Write integration tests for testing the message from #2 + local/global installation

### PR DESCRIPTION
**Pull request by AndyBitz**
Display the correct update command for local and global installations.

Fixes https://github.com/zeit/now-cli/issues/2683

### CODE REVIEW

File: src/util/get-update-command.ts [hunk 1]
```diff
@@ -24,10 +24,91 @@ async function isYarn(): Promise<boolean> {
...
+    join(process.env.HOME || '/', '.npmrc'),
+    process.env.npm_config_globalconfig || process.env.NPM_CONFIG_GLOBALCONFIG
+  ].filter(Boolean);
+
+  for (const configPath of paths) {
+    if (!configPath) {
+      continue;
+    }
+
+    if (await canRead(configPath) === false) {
```
Comment (TooTallNate) [inline src/util/get-update-command.ts]: I'd prefer to just do the `readFile()` operation, and then handle the errors appropriately in a try/catch.

File: src/util/get-update-command.ts [hunk 2]
```diff
@@ -24,10 +24,76 @@ async function isYarn(): Promise<boolean> {
...
+    join(process.env.HOME || '/', '.npmrc'),
+    process.env.npm_config_globalconfig || process.env.NPM_CONFIG_GLOBALCONFIG
+  ].filter(Boolean);
+
+  for (const configPath of paths) {
+    if (!configPath) {
+      continue;
+    }
+
+    const content = await readFile(configPath)
```
Comment (TooTallNate) [inline src/util/get-update-command.ts:39]: Don't we want to try/catch this so that if one of the paths fails then the for loop continues processing?

File: src/util/get-update-command.ts [hunk 3]
```diff
@@ -24,10 +24,76 @@ async function isYarn(): Promise<boolean> {
   return !('_id' in pkg);
 }
 
+async function getConfigPrefix() {
+  const paths = [
+    process.env.npm_config_userconfig || process.env.NPM_CONFIG_USERCONFIG,
```
Comment (TooTallNate) [inline src/util/get-update-command.ts:29]: Are these uppercase env vars actually a thing? I've never seen npm set uppercase env vars.

File: src/util/get-update-command.ts (hunk 2 above)
Comment (AndyBitz) [reply src/util/get-update-command.ts:39]: @TooTallNate it does, check the lines below, there is a `.catch`

File: src/util/get-update-command.ts (hunk 3 above)
Comment (AndyBitz) [reply src/util/get-update-command.ts:29]: They were always displayed with `$NPM_CONFIG_USERCONFIG` instead of `$npm_config_userconfig`, so I just want to be sure here

Comment (TooTallNate) [reply src/util/get-update-command.ts:29]: Sounds good 👍

File: src/util/get-update-command.ts [hunk 4]
```diff
@@ -24,10 +24,76 @@ async function isYarn(): Promise<boolean> {
...
+    );
+
+    if (!prefixPath) {
+      return true;
+    }
+
+    return installPath.startsWith(await realpath(prefixPath));
+  } catch (_) {
+    // Default to global
+    console.error(_);
```
Comment (TooTallNate) [inline src/util/get-update-command.ts]: Leftover?

Comment (AndyBitz) [reply src/util/get-update-command.ts]: Oh, right

Comment (AndyBitz) [reply src/util/get-update-command.ts]: Removed it

**Review by TooTallNate — APPROVED** [review]
