### PR TITLE
[now dev] Inherit env vars from `now.json`

### LINKED ISSUE #2235: [now dev] Build env not passed to client
Using most up to date canary branch: 15.0.8-canary.1.

A couple of versions ago all of this was working, but now the build env variables that I'm passing to client side env are being set with `undefined`.

I have this next.config.js

```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
      ? require('next/constants')
      : require('next-server/constants');

const config = {
    target: 'serverless',
    env: {
        HASURA_URL: process.env.HASURA_URL,
        BASE_URL: process.env.BASE_URL
    }
}
module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    console.log("HASURA URL!!!", process.env.HASURA_URL)
    return config
  }
  const withCSS = require('@zeit/next-css')
  return withCSS(config);
}
```

And these are env sections from now.json

```
    "env": {
        "HASURA_URL": "http://localhost:8080/v1alpha1/graphql",
        "BASE_URL": "http://localhost:3000"
    },
    "build": {
        "env": {
            "BASE_URL": "http://localhost:3000",
            "HASURA_URL": "http://localhost:8080/v1alpha1/graphql"
        }
    },
```

Strangely this was all working perfectly, and then I added the BASE_URL value to build.env and did `now dev` in the terminal and received this error: `Cannot find module '/home/agstover/.cache/co.zeit.now/dev/builders/node_modules/@now/next'`

I ran it again and it worked, but these issues started appearing. Can't get env variables on client and a constant stream of "http://localhost:3000/_next/on-demand-entries-ping?page=/ 404 (Not Found)" in the browser console.

The repo can be found here: https://github.com/agstover/awesomex

### PR DESCRIPTION
**Pull request by TooTallNate**
Before it was only using env vars defined in the `.env` and `.env.build` dotenv files.

Fixes #2235.

### CODE REVIEW

File: src/commands/dev/lib/dev-server.ts [hunk 1]
```diff
@@ -398,13 +398,15 @@ export default class DevServer {
 
     // Retrieve the path of the native module
     const modulePath = await getModuleForNSFW(this.output);
+    const nowJson = await this.getNowJson();
```
Comment (styfle) [inline src/commands/dev/lib/dev-server.ts:394]: I had a bug before when retrieving now.json before `this.env` was assigned because of the validator. Does this fix that bug?

**Review by styfle — APPROVED** [review]

File: src/commands/dev/lib/dev-server.ts (hunk 1 above)
Comment (TooTallNate) [reply src/commands/dev/lib/dev-server.ts:394]: Great catch, fixing.

Comment (styfle) [reply src/commands/dev/lib/dev-server.ts:394]: I personally prefer a more functional approach: the validators should accept all parameters and not rely on `this` state.

**Review by styfle — APPROVED** [review]
Looks much better, thanks 👍

**Review by leo — APPROVED** [review]
