### PR TITLE
[now-cli] Prevent framework from clearing console in `now dev`

### LINKED ISSUE #3497: [dev] Now dev fails to serve api functions when used with Gridsome
Following the [Gridsome example project](https://github.com/zeit/now-examples/blob/master/gridsome) and executing `now dev` will lunch the Gridsome Dev mode but the Now api functions will be ignored.

A solution is to remove the `dev` script from the package.json, but it is not clear then if its a bug or a missconfiguration as the documentation and the example encourages setting the script.

### PR DESCRIPTION
**Pull request by styfle**
When running a framework like Create React App or Gridsome, the console gets cleared. This prevented the user from seeing the message printed from `now dev` which is typically `http://localhost:3000`. Instead the user would see the framework's URL such as `http://localhost:54684`.

See #3497 for an example.

The solution is to change the child process to pipe stdout/stderr. Since most frameworks detect [`process.stdout.isTTY`](https://github.com/facebook/create-react-app/blob/7e6d6cd05f3054723c8b015c813e13761659759e/packages/react-scripts/scripts/start.js#L141-L143) before clearing the console, this will solve the problem. I was also able to intercept stdout to replace the framework's port with the `now dev` port and I think this will also help prevent confusion.

I also had to set `FORCE_COLOR=1` to avoid losing ANSI colors.

- Related to https://github.com/facebook/create-react-app/issues/2495
- Fixes #3497

### CODE REVIEW

**Review by AndyBitz — APPROVED** [review]

**Comment by TooTallNate** [comment]
I'd prefer not losing ANSI colors 😟.
This PR invalidates https://github.com/zeit/now/pull/3112 and https://github.com/zeit/now/pull/3113.

**Comment by styfle** [comment]
@TooTallNate Thanks, I added `FORCE_COLOR=1` and tested Next.js, Create React App, and Gridsome. All are showing ANSI colors correctly 🌈

**Comment by TooTallNate** [comment]
Well, alright. It's a bit hacky IMO since it's specific to `chalk`, but considering the other fixes in this PR maybe the tradeoff is ok.

**Comment by styfle** [comment]
Yep, its actually a feature of [`supports-color`](https://www.npmjs.com/package/supports-color) which has even wider usage than `chalk`.

File: packages/now-cli/src/util/dev/server.ts [hunk 1]
```diff
@@ -1706,7 +1710,29 @@ export default class DevServer {
...
+      if (data) {
+        this.output.debug(`Replacing framework output with now dev address`);
+        data = data
+          .toString()
+          .replace(`http://localhost:${port}`, this.address);
+      }
+      process.stdout.write(data);
+    });
+
+    p.stderr.on('data', data => {
```
Comment (TooTallNate) [inline packages/now-cli/src/util/dev/server.ts]: Why not use `.pipe()`?

```suggestion
    p.stderr.pipe(process.stderr);
```

File: packages/now-cli/src/util/dev/server.ts [hunk 2]
```diff
@@ -1706,7 +1710,29 @@ export default class DevServer {
...
+
+    if (!p.stdout || !p.stderr) {
+      throw new Error('Expected child process to have stdout and stderr');
+    }
+
+    p.stdout.on('data', data => {
+      if (data) {
+        this.output.debug(`Replacing framework output with now dev address`);
+        data = data
+          .toString()
```
Comment (TooTallNate) [inline packages/now-cli/src/util/dev/server.ts]: We should invoke `p.stdout.setEncoding('utf8')` rather than `.toString()` on every Buffer.

File: packages/now-cli/src/util/dev/server.ts (hunk 1 above)
Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts]: In case we wanted to transform stderr too? Are there any perf differences here?

**Review by TooTallNate — CHANGES_REQUESTED** [review]
Left a couple comments.

File: packages/now-cli/src/util/dev/server.ts [hunk 3]
```diff
@@ -1706,7 +1710,20 @@ export default class DevServer {
...
+      throw new Error('Expected child process to have standard output');
+    }
+
+    process.stdin.pipe(p.stdin);
+    p.stderr.pipe(process.stderr);
+    p.stdout.setEncoding('utf8');
+    const devPort = new URL(this.address).port;
+
+    p.stdout.on('data', (data: string) => {
+      process.stdout.write(data.replace(port.toString(), devPort));
```
Comment (TooTallNate) [inline packages/now-cli/src/util/dev/server.ts]: Shouldn't the `port` be a global regexp to replace multiple instances?

Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts]: I changed it to a regex, thanks!

File: packages/now-cli/src/util/dev/server.ts (hunk 1 above)
Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts]: Fixed

File: packages/now-cli/src/util/dev/server.ts (hunk 2 above)
Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts]: Fixed

**Review by TooTallNate — APPROVED** [review]

File: packages/now-cli/src/util/dev/server.ts [hunk 4]
```diff
@@ -1706,7 +1710,24 @@ export default class DevServer {
 
     this.output.debug(`Spawning dev command: ${command}`);
 
-    const p = spawnCommand(command, { stdio: 'inherit', cwd, env });
+    const devPort = new URL(this.address).port;
+    const proxyPort = new RegExp(port.toString(), 'g');
```
Comment (TooTallNate) [inline packages/now-cli/src/util/dev/server.ts:1714]: Adding boundary delimiter might be a good idea:

```suggestion
    const proxyPort = new RegExp(`\\b${port}\\b`, 'g');
```

Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts:1714]: I tried this with CRA which is highlighting the port and it didn't work. 

image
