### PR TITLE
[now-dev] Fix .nowignore to match production

### LINKED ISSUE #2224: [now-dev] Fails when using "allow list" (wildcard) syntax in `.nowignore`
The following `.nowignore` will ignore every file except the `src` directory and its contents. It works fine for production deployments but fails in `now dev`.

```.gitignore
*
!src
!src/**
```

Upon further investigation, it appears the `now dev` ignore logic is completely different than the production `now`. These should be unified.

### PR DESCRIPTION
**Pull request by styfle**
Consolidate logic for `.nowignore` so it works properly with `now dev`.

Fixes #2224

### CODE REVIEW

File: src/util/get-files.ts [hunk 1]
```diff
@@ -168,7 +169,7 @@ export async function staticFiles(
   } else {
     // The package.json `files` whitelist still
     // honors ignores: https://docs.npmjs.com/files/package.json#files
-    const search_ = ['.'];
+    const search_ = src ? [src] : ['.'];
```
Comment (styfle) [inline src/util/get-files.ts]: @TooTallNate @leo I wonder why this was hardcoded to an array with a single `.`

Could we avoid looping since there is only ever one element?

Comment (styfle) [reply src/util/get-files.ts]: Looks like an artifact of #1126

Comment (styfle) [reply src/util/get-files.ts]: After reviewing the git history, I think it is safe to change this to:

```ts
const pattern = src ? src : '.';
const search = await glob(pattern, { cwd: path, absolute: true, dot: true });
```

Then we don't need to loop or copy the array.

File: src/util/get-files.ts [hunk 2]
```diff
@@ -141,6 +141,7 @@ const asAbsolute = function(path: string, parent: string) {
 interface StaticFilesOptions {
   output: Output;
   isBuilds: boolean;
+  src?: string;
```
Comment (amio) [inline src/util/get-files.ts:144]: Would be nice to have some comments for these args, or in the function comment for `staticFiles()` is good too.

File: src/commands/dev/lib/dev-server.ts [hunk 3]
```diff
@@ -393,23 +392,29 @@ export default class DevServer {
...
     this.buildEnv = buildEnv;
-
     const nowJson = await this.getNowJson();
+
+    const opts = { output: this.output, isBuilds: true };
+    const files =  await getFiles(this.cwd, nowJson, opts);
+    const results: { [filePath: string]: FileFsRef } = {};
+    for (const fsPath of files) {
+      const path = relative(this.cwd, fsPath);
+      const mode = 33188; // TODO: get the real mode
```
Comment (TooTallNate) [inline src/commands/dev/lib/dev-server.ts]: This needs to be fixed. Note that the previous implementation leveraged the `statsCache` object that `glob` populates as an optimization.

File: src/commands/dev/lib/dev-builder.ts [hunk 4]
```diff
@@ -373,10 +372,11 @@ export async function getBuildMatches(
     }
 
     // TODO: use the `files` map from DevServer instead of hitting the filesystem
```
Comment (TooTallNate) [inline src/commands/dev/lib/dev-builder.ts:374]: It would be nice to tackle this TODO instead of calling `getFiles()` again.

File: src/commands/dev/lib/dev-server.ts (hunk 3 above)
Comment (styfle) [reply src/commands/dev/lib/dev-server.ts]: @TooTallNate Ok I'll look into exposing the `statsCache` somehow from `staticFiles` method.

Comment (styfle) [reply src/commands/dev/lib/dev-server.ts]: @TooTallNate I cheated and just use `stat` again here so we can ship it :shipit:

File: src/commands/dev/lib/dev-builder.ts (hunk 4 above)
Comment (styfle) [reply src/commands/dev/lib/dev-builder.ts:374]: Let's merge this PR for correctness and then do another PR where we measure the bottlenecks and fix performance issues.

**Review by leo — APPROVED** [review]

**Review by TooTallNate — APPROVED** [review]
