### PR TITLE
[now-cli] Fix `localConfig` when file is above the target directory

### LINKED ISSUE #3209: bug: CLI uses folder name instead of `name` property specified in custom config
When running the following command: 

```bash
now ./dist/myproject-dashboard --local-config ./now-staging.json --token ${NOW_TOKEN}
```

With the following `now-staging.json`:

```json
{
  "name": "myproject-dashboard-preview",
  "scope": "myorg",
  "version": 2,
  "alias": "dashboard.preview.myproject.com",
  "routes": [{ "handle": "filesystem" }, { "src": "/.*", "dest": "/index.html" }]
}
```

The CLI will upload the code to a project matching the folder name (`myproject-dashboard`) instead of correctly using the specified `name` in the custom config.

CLI version:
```
❯ now -v 
16.4.3
```

### PR DESCRIPTION
**Pull request by styfle**
Fixes #3209

### CODE REVIEW

File: packages/now-cli/src/commands/deploy/index.js [hunk 1]
```diff
@@ -43,7 +50,7 @@ export default async ctx => {
     paths = [process.cwd()];
   }
 
-  const localConfig = readLocalConfig(paths[0]);
+  const localConfig = ctx.localConfig || readLocalConfig(paths[0]);
```
Comment (styfle) [inline packages/now-cli/src/commands/deploy/index.js]: This is the only line I changed in this file. The rest are from `lint-staged`.

**Review by rdev — APPROVED** [review]
