### PR TITLE
[now-cli] Fix `now alias` with no arguments

### LINKED ISSUE #2941: now alias without any arguments is broken
Hey Zeit team,

It looks like the latest update broke using `now alias` without any arguments.

This seems to be the responsible code: https://github.com/zeit/now/commit/7c421f92e144778c0074a27a212157be9901b681#diff-b79436b8a38c46520f80ad57562b4817R82-R91

We have our alias's set up in JSON config files and I believe the old functionality was such that you could call `now alias` and specify a config with `{ ... "alias": "some-alias.com" ... }` and it would read the alias name from the config and default to the latest deployment when you supplied no arguments. This doesn't appear to be working in our CI/CD anymore:

```
$ now alias --local-config=now.production.json -t TOKEN -T TEAM_NAME
> WARN! The "--team" flag is deprecated. Please use "--scope" instead.
> Error! The provided argument "undefined" is not a valid deployment
```

### PR DESCRIPTION
**Pull request by TooTallNate**
Fixes #2941.

### CODE REVIEW

File: packages/now-cli/src/util/alias/get-inferred-targets.ts [hunk 1]
```diff
@@ -7,7 +7,11 @@ export default async function getInferredTargets(
   output: Output,
   config: Config
 ) {
-  output.warn(`The ${cmd('now alias')} command (no arguments) was deprecated in favour of ${cmd('now --prod')}.`);
+  output.warn(
+    `The ${cmd(
+      'now alias'
+    )} command (no arguments) was deprecated in favor of ${cmd('now --prod')}.`
```
Comment (TooTallNate) [inline packages/now-cli/src/util/alias/get-inferred-targets.ts:13]: Switched spelling of "favour" to "favor" (consistent with the warning on line 18).

File: packages/now-cli/test/integration.js [hunk 2]
```diff
@@ -500,22 +495,67 @@ test('scale the alias', async t => {
...
+  t.true(stdout.startsWith(goal));
+});
+
+test('create an alias from "now.json" `alias` for deployment', async t => {
+  const target = fixture('dockerfile');
+
+  // Add the `alias` field to the "now.json" file
+  const jsonPath = path.join(target, 'now.json');
+  const json = JSON.parse(await readFile(jsonPath, 'utf8'));
+  json.alias = `${session}-from-nowjson.now.sh`;
```
Comment (AndyBitz) [inline packages/now-cli/test/integration.js:527]: Maybe we can use an alias like `${random}.${username}.now.sh`, since the other one could be taken, and then the test would fail.

Comment (TooTallNate) [reply packages/now-cli/test/integration.js:527]: The logic was lifted from the other `now alias` test, but with the "-from-nowjson" portion added. I don't think the collision is very likely, as the `session` is already a randomly generated string.

**Review by AndyBitz — APPROVED** [review]
