### PR TITLE
[cli] Poll the Dev Command server on both IPv4 and IPv6 in `vc dev`

### LINKED ISSUE #8121: `vercel dev` in Vite app causes port timeout
I get the following error after a while running vercel dev in a Vite/SvelteKit app:

```
Error! Detecting port 62323 timed out after 300000ms
Error! An unexpected error occurred!
Error: Detecting port 62323 timed out after 300000ms
    at checkForPort (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243842:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DevServer.runDevCommand (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243643:9)
    at DevServer._start (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243267:9)
Error! An unexpected error occurred!
Error: Detecting port 62323 timed out after 300000ms
    at checkForPort (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243842:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DevServer.runDevCommand (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243643:9)
    at DevServer._start (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243267:9)
```

### PR DESCRIPTION
**Pull request by TooTallNate**
This change will allow the downstream Dev Command server be able to listen on either of `127.0.0.1` for IPv4 or `[::1]` for IPv6.

- Fixes #6639
- Fixes #8511
- Fixes #8121
- Closes #8512
- Closes #8384

### CODE REVIEW

File: packages/cli/src/util/dev/server.ts [hunk 1]
```diff
@@ -2641,15 +2633,29 @@ function needsBlockingBuild(buildMatch: BuildMatch): boolean {
...
+  }
+  return host;
+}
+
+async function getReachableHostOnPort(port: number): Promise<string | false> {
+  const optsIpv4 = { host: '127.0.0.1' };
+  const optsIpv6 = { host: '::1' };
+  const results = await Promise.all([
+    isPortReachable(port, optsIpv4).then(r => r && optsIpv4.host),
+    isPortReachable(port, optsIpv6).then(r => r && `[${optsIpv6.host}]`),
```
Comment (styfle) [inline packages/cli/src/util/dev/server.ts:2655]: Should the brackets be includes in the optsIpv6 on line 2653 above?

File: packages/cli/src/util/dev/server.ts [hunk 2]
```diff
@@ -2641,15 +2633,29 @@ function needsBlockingBuild(buildMatch: BuildMatch): boolean {
...
+  ]);
+  return results.find(Boolean) || false;
```
Comment (styfle) [inline packages/cli/src/util/dev/server.ts:2658]: What about if both are found? Looks like this will favor ipv4 over ipv6, is that intended?

File: packages/cli/src/util/dev/server.ts (hunk 1 above)
Comment (TooTallNate) [reply packages/cli/src/util/dev/server.ts:2655]: No because you don't use the brackets in the `host` parameter of `net.connect()`/`http.request()`/etc. The brackets are only required in a URL.

File: packages/cli/src/util/dev/server.ts (hunk 2 above)
Comment (TooTallNate) [reply packages/cli/src/util/dev/server.ts:2658]: If both are reachable then it shouldn't really matter. But we could swap to prefer IPv6.

Comment (styfle) [reply packages/cli/src/util/dev/server.ts:2658]: I think since Node.js prefers ipv6 by default, we probably should too

**Review by styfle — COMMENTED** [review]
We also have a similar implementation in `@vecel/static-build` but I'm not sure if its still used (perhaps if `builds` is defined)

https://github.com/vercel/vercel/blob/2b57e12ad39687fd9225e5390da29c342c55130f/packages/static-build/src/index.ts#L52

**Comment by TooTallNate** [comment]
Ya the `@vercel/static-build` version won't be used in most cases. We should probably remove it anyways.

**Review by styfle — APPROVED** [review]
Thanks! 🎉
