### PR TITLE
[remix] Fix POST requests when `unstable_singleFetch` is enabled

### LINKED ISSUE #124: Error when using `VERCEL_REMIX_NATIVE_FETCH` with POST requests
When enabling single fetch using `VERCEL_REMIX_NATIVE_FETCH=1`, POST requests result in an error. This occurs after deploying to Vercel.

### Reproduction

Repository: https://github.com/coji/vercel-remix-singlefetch-test

Here's the relevant code causing the issue:

```jsx
import { Form, useActionData } from '@remix-run/react';
import { unstable_defineAction as defineAction } from '@vercel/remix';

export const action = defineAction(async () => {
  return { message: 'Hello, world!' };
});

export default function Post() {
  const actionData = useActionData<typeof action>();

  return (
    <div className="px-4 py-2">
      <h1>Vercel Remix Single Fetch Test</h1>

      <Form method="POST">
        <button className="mt-2 rounded-md bg-indigo-600 px-2.5 py-1.5 font-semibold text-white shadow-sm hover:bg-indigo-500">
          Submit
        </button>

        {actionData && (
          <div className="mt-2 border rounded p-2">{actionData.message}</div>
        )}
      </Form>
    </div>
  );
}
```

Deployed URL: https://vercel-remix-singlefetch-test.vercel.app/

### Steps to reproduce

1. Deploy the code to Vercel with `VERCEL_REMIX_NATIVE_FETCH=1` set in the environment variables.
2. Visit the deployed URL and click the "Submit" button to trigger a POST request.

### Expected behavior

The POST request should succeed, and the message "Hello, world!" should be displayed.

### Actual behavior

The POST request fails, and the following client-side error is displayed:

```
Error: Unable to decode turbo-stream response from URL: https://vercel-remix-singlefetch-test.vercel.app/_root.data?index
```

Additionally, the following server-side error appears in the Vercel logs:
```
TypeError: RequestInit: duplex option is required when sending a body.
at new Request (/var/task/node_modules/.pnpm/undici@6.19.2/node_modules/undici/lib/web/fetch/request.js:539:15)
at createRemixRequest (file:///var/task/build/server/nodejs-eyJydW50aW1lIjoibm9kZWpzIn0/server-index.mjs:61:10)
at Server.default (file:///var/task/build/server/nodejs-eyJydW50aW1lIjoibm9kZWpzIn0/server-index.mjs:80:19)
at /opt/rust/nodejs.js:8:3973
at AsyncLocalStorage.run (node:async_hooks:346:14)
at /opt/rust/nodejs.js:8:3961
at AsyncLocalStorage.run (node:async_hooks:346:14)
at Server.<anonymous> (/opt/rust/nodejs.js:8:3949)
at Server.s (/opt/rust/nodejs.js:8:824)
at Server.emit (node:events:519:28)
```

### Additional context

This issue seems to be related to the `duplex` option in the fetch API when using `VERCEL_REMIX_NATIVE_FETCH=1`. The error suggests that this option is required when sending a body, but it's not being set correctly in the current implementation.

It's worth noting that the Remix core has addressed this issue by setting `duplex: 'half'` when there's a request body. This can be seen in the Remix source code:

https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/single-fetch.ts#L151

```typescript
export async function singleFetchAction(
  serverMode: ServerMode,
  staticHandler: StaticHandler,
  request: Request,
  handlerUrl: URL,
  loadContext: AppLoadContext,
  handleError: (err: unknown) => void
): Promise<{ result: SingleFetchResult; headers: Headers; status: number }> {
  try {
    let handlerRequest = new Request(handlerUrl, {
      method: request.method,
      body: request.body,
      headers: request.headers,
      signal: request.signal,
      ...(request.body ? { duplex: "half" } : undefined),
    });
    // ...
```

This suggests that the vercel/remix-builder implementation might need to incorporate a similar approach to resolve the current error.

Any assistance in resolving this issue would be greatly appreciated. Thank you!

### PR DESCRIPTION
**Pull request by TooTallNate**
Fixes https://github.com/vercel/remix/issues/124.

Also fixes the CI configuration so that the `vitest-e2e` tests are properly run.

### CODE REVIEW

File: packages/remix/defaults/server-node.mjs [hunk 1]
```diff
@@ -55,7 +56,8 @@ function createRemixRequest(req, res) {
   };
 
   if (req.method !== 'GET' && req.method !== 'HEAD') {
-    init.body = req;
+    init.body = createReadableStreamFromReadable(req);
```
Comment (TooTallNate) [inline packages/remix/defaults/server-node.mjs:59]: This matches the behavior of the `remix-serve` CLI:

https://github.com/remix-run/remix/blob/44d1cc61069ec29cb271f50ea1be58c21979785e/packages/remix-express/server.ts#L111-L112

**Review by trek — DISMISSED** [review]

**Review by EndangeredMassa — DISMISSED** [review]

**Review by jeffsee55 — APPROVED** [review]
