### PR TITLE
[cli] Support WebSocket upgrades in dev

### LINKED ISSUE #3451: [now dev] Reloading not supported on CRA project
`now dev` then spins up it's own server and proxies request to the underlying CRA dev server. 

I have noticed that the `/sockjs-node` websocket requests never get proxied correctly, and therefore we can't support auto page reload, or react hot loader / react fast refresh (via react app rewired).

---

**Observations**

It appears that when running `now dev` it actually makes the underlying CRA dev server run on a random port, for e.g 49426. The actual `now dev` server runs on the typical port that CRA would normally run on, i.e. 3000. This confused me a bit but I eventually figured out what was going on.

That all being said, if I load the CRA dev server directly (i.e. utilising the random port, e.g. 49426) then I notice the `/sockjs-node` requests resolving correctly.  It's only when I use the `now dev` proxy server (i.e. 3000) that the requests do not resolve.

---

**Steps to reproduce**

1. Create a new black CRA project
2. Add the script:
    ```
    "dev": "BROWSER=none react-scripts start"
    ```
3. Run `now dev`
4. Open browser on http://localhost:3000
5. Open dev tools and note the `/sockjs-node` request never resolving

---

Without this request proxying correctly we can never get hot reloading working as rad as it could. With the new React Fast Refresh around the corner it would be great to get the `now dev` server ready to support this.

### PR DESCRIPTION
**Pull request by matchu**
We were already using `http-proxy`'s WebSockets option, but we were missing a step! In addition to setting `{ws: true}`, you must also forward WebSocket upgrade events from the front-facing server to the proxy. [(See this example.)](https://github.com/http-party/node-http-proxy#proxying-websockets)

Previously, the proxy server and client _would_ mutually agree to "upgrade" their connection (because we set `{ws: true}`)… but then, when the client would start sending WebSocket data instead of HTTP data, our front-facing server would drop it, because we hadn't configured a place for it to go.

In this change, we configure `this.server` to forward its `upgrade` events to the proxy server.

We also refactor `proxyPass` to use the new shared `this.proxy` instance responsible for the `upgrade` events, instead of creating a new proxy instance for every request. This isn't strictly necessary, but a helpful simplification to clarify that there's no specific reason for the proxy instances to be _different_ than the instance that manages WebSocket upgrades!

This fixes #3451: CRA apps can now auto-refresh when the source code changes, and Firefox can now load the app without crashing on the 6th attempt.

### CODE REVIEW

File: packages/now-cli/src/util/dev/server.ts [hunk 1]
```diff
@@ -826,6 +832,13 @@ export default class DevServer {
     // Wait for "ready" event of the watcher
     await once(this.watcher, 'ready');
 
+    // Configure the server to forward WebSocket "upgrade" events to the proxy.
+    this.server.on('upgrade', (req, socket, head) => {
+      this.proxy.ws(req, socket, head, {
+        target: `http://localhost:${this.devProcessPort}`,
+      });
+    });
+
```
Comment (matchu) [inline packages/now-cli/src/util/dev/server.ts]: Wondering how y'all feel about placement for this. `start` was my best guess, but I wasn't sure on that (it _could_ go in the constructor, I think?), and I wasn't sure this was the right place in `start`.

Setting up event handlers felt start-y to me, and I noticed not much other substantive things happening in the constructor… though I suppose we could refactor the callback here to be a method, and then configuring it in the constructor would be pretty concise?

File: packages/now-cli/src/util/dev/server.ts [hunk 2]
```diff
@@ -1767,30 +1782,26 @@ function proxyPass(
...
 
-  proxy.on('error', (error: NodeJS.ErrnoException) => {
-    // If the client hangs up a socket, we do not
-    // want to do anything, as the client just expects
-    // the connection to be closed.
-    if (error.code === 'ECONNRESET') {
-      res.end();
-      return;
+      output.error(`Failed to complete request to ${req.url}: ${error}`);
     }
```
Comment (matchu) [inline packages/now-cli/src/util/dev/server.ts:1924]: I think I was able to verify this refactor, by closing a tab and confirming that I _didn't_ see "Failed to complete request…" in the debug output?

File: packages/now-cli/src/util/dev/server.ts [hunk 3]
```diff
@@ -826,6 +832,13 @@ export default class DevServer {
     // Wait for "ready" event of the watcher
     await once(this.watcher, 'ready');
 
+    // Configure the server to forward WebSocket "upgrade" events to the proxy.
+    this.server.on('upgrade', (req, socket, head) => {
+      this.proxy.ws(req, socket, head, {
+        target: `http://localhost:${this.devProcessPort}`,
```
Comment (matchu) [inline packages/now-cli/src/util/dev/server.ts]: I'm also wondering about setting `target` here like this… I copied it from a `proxyPass` call site.

I think it could also be interesting to configure this as the default `target`, and have other calls _override_ the `target` option when they want to? I didn't look too deeply into what the override cases are doing though, or when `devProcessPort` is initialized (so I'm not actually sure configuring this at construction time would be possible).

**Comment by matchu** [comment]
Hmm not sure how to fix the integration tests! They're failing with `Error: Failed to create test deployment. Did you forget to set NOW_TOKEN?`, which sounds like maybe I missed some setup to get Now CI deployment working from my account?

**Comment by styfle** [comment]
Hi @matchu thanks for this PR!

GitHub Actions CI doesn't include secrets for forks so that's why you're seeing that error. We just recently added deployments so that `now dev` can compare against real deployments. If you want to run `yarn test-integration-dev` locally, you can set `NOW_TOKEN` to the token found in `~/.now/auth.json` or you can modify testFixtureStdio and set `skipDeploy=true`.

That said, this PR looks good but we'll have @TooTallNate take a look too, thanks!

**Review by styfle — DISMISSED** [review]
This is wonderful, thanks! 🎉

**Review by TooTallNate — DISMISSED** [review]
This looks great! Thanks @matchu 👍

**Comment by matchu** [comment]
👍🏻 The integration tests seemed good locally! 🤞

I'm a bit new to OSS PR workflows, is there a next step on my end, or will y'all merge when convenient? (I did just now click an "Update branch" button on this page, in case that was a blocker!)

(this isn't me being impatient or trying to rush you, just me being anxious about whether I'm understanding the flow correctly 😅)

**Comment by TooTallNate** [comment]
Nothing left to do on your end @matchu. We will merge your PR shortly. Thanks for the PR!

**Comment by matchu** [comment]
great thankyou! 😊 love the tool, appreciate the work!!

**Review by ctrlplusb — DISMISSED** [review]

**Comment by styfle** [comment]
Sorry about the delay, there is a lot of churn the last couple of days as we prepare to rename the CLI and other packages. We'll circle back here soon, thanks for being patient!

File: packages/now-cli/src/util/dev/server.ts (hunk 1 above)
Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts]: I think `start()` is fine. The only better place might be immediately after the port is assigned. But let's keep it here for now 👍

**Review by styfle — APPROVED** [review]
Confirmed that this works with CRA and passes existing tests.

Great work! 🎉

**Comment by styfle** [comment]
Shipped to the canary channel. Try it out with `npm i -g vercel@canary`.

**Comment by TooTallNate** [comment]
@matchu Please see #4408 and let me know if that makes sense to you.

**Comment by styfle** [comment]
@TooTallNate I added that line in the cleanup commit 1ac9707c460caf9adfa80aba84129573976110f7 so PR #4408 looks good 👍

**Comment by matchu** [comment]
Looking good in canary for me too! thanks!

**Comment by felixheck** [comment]
I just tried it and now the HMR of `@nuxt/content` works.
Thanks a lot!
