### PR TITLE
[now-next] Handle symlinks in createPseudoLayer

### LINKED ISSUE #3400: Error: EISDIR: illegal operation on a directory when deploying on Now
A couple issues with now + next.js seem to be caused by this module when run with yarn workspaces and tracing out of the workspace root.

Running locally is not an issue, but it fails on zeit now.

- https://spectrum.chat/zeit/now/deployment-failed-error-eisdir-illegal-operation-on-a-directory~1610db37-38fa-4ac8-ab9f-dc25888ef18b
- https://spectrum.chat/zeit/now/error-deploying-next-js-monorepo-on-now~99acb8f4-1648-4422-91ea-ca243195fbc4

[My log](https://gist.github.com/darknoon/bfa10f31b0f9054ce735a784fe12f10f)

### PR DESCRIPTION
**Pull request by ijjk**
This makes sure to handle symlinks created in mono repos while creating the zip for a lambda based page in Next.js

Fixes #3400

### CODE REVIEW

File: packages/now-next/src/utils.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@ import {
   Lambda,
   Route,
 } from '@now/build-utils';
+import { isSymbolicLink } from '@now/build-utils/dist/fs/download';
```
Comment (styfle) [inline packages/now-next/src/utils.ts]: Let's export this from the build-utils index file since we use it in a couple builders

File: packages/now-next/test/fixtures/09-mono-repo/now.json [hunk 2]
```diff
@@ -0,0 +1,11 @@
+{
```
Comment (styfle) [inline packages/now-next/test/fixtures/09-mono-repo/now.json]: Nit pick: can you rename `09-mono-repo` to `09-yarn-workspace` so its a little more specific?

File: packages/now-next/src/utils.ts [hunk 3]
```diff
@@ -455,9 +457,13 @@ export const ExperimentalTraceVersion = `9.0.4-canary.1`;
...
-    crc32: number;
-    compBuffer: Buffer;
-    uncompressedSize: number;
+    crc32?: number;
+    compBuffer?: Buffer;
+    uncompressedSize?: number;
+
+    file?: FileFsRef;
+    isSymlink?: boolean;
+    symlinkTarget?: string;
```
Comment (styfle) [inline packages/now-next/src/utils.ts]: I think you can be more specific here:

```ts
export type PseudoLayer = {
  [fileName: string]: PseudoFile | PseudoSymbolicLink
}

export type PseudoFile = {
  isSymlink: false;
  crc32: number;
  compBuffer: Buffer;
  uncompressedSize: number;
}

export type PseudoSymbolicLink = {
  isSymlink: true;
  file: FileFsRef;
  symlinkTarget: string;
}
```

Comment (ijjk) [reply packages/now-next/src/utils.ts]: That looks better 👍

File: packages/now-next/test/fixtures/09-mono-repo/now.json (hunk 2 above)
Comment (ijjk) [reply packages/now-next/test/fixtures/09-mono-repo/now.json]: Renamed

File: packages/now-next/src/utils.ts (hunk 1 above)
Comment (ijjk) [reply packages/now-next/src/utils.ts]: Updated

File: packages/now-next/src/utils.ts [hunk 4]
```diff
@@ -520,10 +540,31 @@ export async function createLambdaFromPseudoLayers({
   const zipFile = new ZipFile();
   const addedFiles = new Set();
 
+  const names = Object.keys(files).sort();
```
Comment (styfle) [inline packages/now-next/src/utils.ts:543]: What's the purpose of `sort()` here?

Comment (ijjk) [reply packages/now-next/src/utils.ts:543]: Not sure, maybe was originally added for consistency. I pulled this logic from `createLambda` [here](https://github.com/zeit/now/blob/17687e9bcd9fa32e271849505fd666093d1788a8/packages/now-build-utils/src/lambda.ts#L107)

**Review by styfle — COMMENTED** [review]
The code looks good!

However this still fails for the original repo:

https://github.com/benawad/now-mono-problem

**Review by styfle — APPROVED** [review]
Looks good, thanks! 🎉
