### PR TITLE
[now-ruby] Use pre-installed ruby 2.5

### LINKED ISSUE #2998: Is Rails supported on Now?
OS: `OSX 10.14.6`
Node: `10.16.0`
Ruby: `2.6.1`
Now CLI `16.1`
Rails: `6.0`

Hi,

I'm having issues running Rails locally using `now dev` and on `now`.

Locally with `now dev`
Reproduction steps:
1. `rails new rails-app`
2. Create a `now.json` with contents:
```json
{
  "version": 2,
  "builds": [
    {
      "src": "rails-app/config.ru",
      "use": "@now/ruby"
    }
  ],
  "routes": [{ "src": "/", "dest": "rails-app/config.ru" }]
}

```
3. `now dev` yields:
```sh
> Creating initial build

> Error! Command failed with exit code 2 (ENOENT): yum install -y git gcc make tar bzip2 readline-devel openssl-devel ruby-devel zlib-devel
spawn yum ENOENT
```

On `now`
1. `rails new rails-app`
2. Create a `now.json` with contents:
```json
{
  "version": 2,
  "builds": [
    {
      "src": "rails-app/config.ru",
      "use": "@now/ruby"
    }
  ],
  "routes": [{ "src": "/", "dest": "rails-app/config.ru" }]
}
```
3.  Now yields:
```sh
yarn info @now/build-utils@latest...
yarn info @now/ruby...
yarn add @now/build-utils@0.10.0...
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @now/build-utils@0.10.0
info All dependencies
└─ @now/build-utils@0.10.0
Done in 0.56s.
yarn add @now/ruby@0.1.6...
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @now/ruby@0.1.6
info All dependencies
└─ @now/ruby@0.1.6
Done in 1.10s.
TypeError: util.getSystemErrorName is not a function
    at getCode (/tmp/e97d8416e11caeb8/.build-utils/.builder/node_modules/@now/ruby/dist/index.js:28461:16)
    at makeError (/tmp/e97d8416e11caeb8/.build-utils/.builder/node_modules/@now/ruby/dist/index.js:28500:35)
    at handlePromise (/tmp/e97d8416e11caeb8/.build-utils/.builder/node_modules/@now/ruby/dist/index.js:3759:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
worker exited with code 20 and signal null
done
done
```

Deployment URL: rails-64wuh4wd8.now.sh

Any idea what this could be?

### PR DESCRIPTION
**Pull request by styfle**
This PR will improve performance of `@now/ruby` deployments since it will not need to install ruby each time. We already have ruby 2.5 in the build environment so this PR makes the builder aware of that path.

I am still installing the bundler to avoid the conflicting versions since ruby 2.6 is installed in the PATH.

### Benchmark

- 01-cowsay (11s)
- 02-cowsay-vendored (30s)
- 03-cowsay-proc (11s)
- 04-cowsay-vendored-nested (28s)
- 05-sinatra (14s)
- 06-rails (74s)

cc @nathancahill

This also adds a polyfill for Node 10 to fix #2998

### CODE REVIEW

**Comment by styfle** [comment]
@nathancahill Oddly enough, this seemed to perform better in 376ffe0cfa9f0215628cbb329fe10ee5929fbc1f than it did in cfa1d61c725e4be7ea6f67f4c88c450c808d80e4 and tests pass for both.

Now that the builder will share the same ruby installation for all builds, does GEM_HOME matter either way?

File: packages/now-ruby/polyfill.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// Add a polyfill for Node 8 to fix ncc.
+// We can delete this once fargate defaults to Node 10.
+const util = require('util');
+if (!util.getSystemErrorName) {
+  util.getSystemErrorName = function getSystemErrorName(err: number) {
```
Comment (TooTallNate) [inline packages/now-ruby/polyfill.ts:5]:
```suggestion
  util.getSystemErrorName = function getSystemErrorName(err: NodeJS.ErrnoException): string {
```

File: packages/now-ruby/polyfill.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
...
+    return `Unknown system error ${err}`;
```
Comment (TooTallNate) [inline packages/now-ruby/polyfill.ts:6]:
```suggestion
    return err.code || `Unknown system error ${err}`;
```

**Review by TooTallNate — APPROVED** [review]

File: packages/now-ruby/polyfill.ts (hunk 1 above)
Comment (styfle) [reply packages/now-ruby/polyfill.ts:5]: I don't think this is correct. The Node implementation maps a number, such as `-3`, to an error string such as `ESRCH`.

Try it:

```
> util.getSystemErrorName(-3)
'ESRCH'
> util.getSystemErrorName(new Error('wat'))
TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type object
```
