### PR TITLE
[next] Fix missing app route with mixed SSR/SSG dynamic route

### LINKED ISSUE #62634: Next in Vercel - SSG page with fetch `cache: no-store` responds with `404 Not Found` page
### Link to the code that reproduces this issue

https://github.com/fullyherge/vercel-cache-repro

### To Reproduce

1. Install dependencies
2. Run locally - `npm run build` => `npm run start`
3. Go to `localhost:3000/no-store` and note that it functions
4. Deploy to Vercel - `vercel link` => `vercel deploy`
5. Go to the deployed site (mine is here: [`no-store`](https://vercel-cache-repro-fullystudios-fully-studios-team.vercel.app/no-store))
6. Note that it does not function - instead gives `404 Not Found`

### Current vs. Expected behavior

It gives an error.
I expect the page to render, just like in local environment.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.2 // Also tested v20
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: 8.9.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0 // Also tested on canary
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

Also posted my initial discussion here: https://github.com/orgs/vercel/discussions/5935

### PR DESCRIPTION
**Pull request by ijjk**
Fixes: https://github.com/vercel/next.js/issues/62634

### CODE REVIEW

File: packages/next/src/server-build.ts [hunk 1]
```diff
@@ -1403,6 +1403,10 @@ export async function serverBuild({
 
   prerenderRoutes.forEach(route => {
     if (experimentalPPRRoutes.has(route)) return;
+    // we can't delete app route lambdas just because
+    // the are in the prerender manifest since a dynamic
```
Comment (ztanner) [inline packages/next/src/server-build.ts]:
```suggestion
    // they are in the prerender manifest since a dynamic
```

File: packages/next/src/server-build.ts [hunk 2]
```diff
@@ -1403,6 +1403,10 @@ export async function serverBuild({
...
+    // route can have some prerendered paths and the reset SSR
```
Comment (ztanner) [inline packages/next/src/server-build.ts]:
```suggestion
    // route can have some prerendered paths and the rest SSR
```

**Review by ztanner — DISMISSED** [review]

**Review by ztanner — DISMISSED** [review]

**Review by TooTallNate — APPROVED** [review]

**Review by ztanner — APPROVED** [review]
