### PR TITLE
[next] Ensure revalidation works with i18n

### LINKED ISSUE #18503: [10.0.0][i18n][Vercel] a full-page reload occur on page transitions
# Bug report

## Describe the bug

I use the `i18n` feature. Following links using `next/link` does a full page reload. This happens only when an app is deployed to Vercel.

## To Reproduce

Repository: [next.js-bug-i18n-reload](https://github.com/rokinsky/next.js-bug-i18n-reload)

1. Deploy the app to Vercel
2. Go to the website, e.g. [https://next-js-bug-i18n-reload.vercel.app](https://next-js-bug-i18n-reload.vercel.app)
3. Follow the listed links
4. See full page reload (pay attention to favicon if you use Chrome)

## Expected behavior

No page reloading

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Next.js: 10.0.0
- Version of Node.js: v10.22.1

## Additional context

Works great locally in dev and prod modes.

### PR DESCRIPTION
**Pull request by ijjk**
This corrects some i18n pages being considered staticPages instead of prerender items which was breaking revalidate behavior. This also adds more verbose tests for i18n ensuring revalidation is working correctly

x-ref: https://github.com/vercel/next.js/discussions/18443
Fixes: https://github.com/vercel/next.js/issues/18503

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

File: packages/now-next/src/index.ts [hunk 1]
```diff
@@ -1540,7 +1544,7 @@ export const build = async ({
 
                   if (!currentPage) {
                     console.error(
-                      "Failed to find matching page for", toRender, "in lambda"
+                      "Failed to find matching page for", {toRender, header: req.headers['x-nextjs-page'], url: req.url, pages: Object.keys(pages) }, "in lambda"
```
Comment (styfle) [inline packages/now-next/src/index.ts:1547]: Logging all page keys might get big, right? We have a max chars per log so maybe this should be a separate console.error()?

**Review by styfle — APPROVED** [review]

**Review by Timer — APPROVED** [review]
