### PR TITLE
Account for npm being down

### LINKED ISSUE #1345: `now` fails because of npm being down
Upon `now --version` I get this:
```
[2018-05-15 18:00:24]   Error: Request failed with code 503
[2018-05-15 18:00:24]     at ClientRequest.response (/snapshot/repo/node_modules/update-check/index.js:83:18)
[2018-05-15 18:00:24]     at Object.onceWrapper (events.js:254:19)
[2018-05-15 18:00:24]     at ClientRequest.emit (events.js:159:13)
[2018-05-15 18:00:24]     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
[2018-05-15 18:00:24]     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
[2018-05-15 18:00:24]     at TLSSocket.socketOnData (_http_client.js:439:20)
[2018-05-15 18:00:24]     at TLSSocket.emit (events.js:159:13)
[2018-05-15 18:00:24]     at addChunk (_stream_readable.js:265:12)
[2018-05-15 18:00:24]     at readableAddChunk (_stream_readable.js:252:11)
[2018-05-15 18:00:24]     at TLSSocket.Readable.push (_stream_readable.js:209:10) Error: Request failed with code 503
[2018-05-15 18:00:24]     at ClientRequest.response (/snapshot/repo/node_modules/update-check/index.js:83:18)
[2018-05-15 18:00:24]     at Object.onceWrapper (events.js:254:19)
[2018-05-15 18:00:24]     at ClientRequest.emit (events.js:159:13)
[2018-05-15 18:00:24]     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
[2018-05-15 18:00:24]     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
[2018-05-15 18:00:24]     at TLSSocket.socketOnData (_http_client.js:439:20)
[2018-05-15 18:00:24]     at TLSSocket.emit (events.js:159:13)
[2018-05-15 18:00:24]     at addChunk (_stream_readable.js:265:12)
[2018-05-15 18:00:24]     at readableAddChunk (_stream_readable.js:252:11)
[2018-05-15 18:00:24]     at TLSSocket.Readable.push (_stream_readable.js:209:10)
```

### PR DESCRIPTION
**Pull request by leo**
This PR...

- ...corrects the file names for `README.md` and `LICENSE`
- ...adds `.editorconfig`
- ...prevents the update checking from crashing the CLI if an error occurs

💅 

This closes #1345.

### CODE REVIEW

File: src/now.js [hunk 1]
```diff
@@ -53,10 +53,16 @@ const main = async (argv_) => {
...
-    distTag: pkg.version.includes('canary') ? 'canary' : 'latest'
-  })
+  let update = null
+
+  try {
+    update = await checkForUpdate(pkg, {
+      interval: ms('1d'),
+      distTag: pkg.version.includes('canary') ? 'canary' : 'latest'
+    })
+  } catch (err) {
```
Comment (leo) [inline src/now.js]: I don't have access to the `--debug` flag here, otherwise I'd show the full error in debug mode.

File: src/now.js [hunk 2]
```diff
@@ -53,10 +53,16 @@ const main = async (argv_) => {
...
+    console.log(error('Checking for updates failed'))
```
Comment (jamo) [inline src/now.js]: should we log the error with `-d`?

File: .editorconfig [hunk 3]
```diff
@@ -0,0 +1,37 @@
+root = true
+
+[*]
+indent_style = space
```
Comment (leo) [inline .editorconfig:4]: This is only temporary, until we add our linting setup for the whole repo (then we'll switch to tabs). I didn't want to do it now, because it's a huge diff.

**Review by jamo — APPROVED** [review]

**Review by matheuss — COMMENTED** [review]
LGTM
