### PR TITLE
[next] fix content-type for RSC prefetches

### LINKED ISSUE #54934: Whole page component re-renders (unmounts) when route changes
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/optimistic-panna-dgh66c

### To Reproduce

–

### Current vs. Expected behavior

Locally, this runs as expected and does not re-render the layout. When deployed to Vercel however, it re-renders the layout for whatever reason. Local version on Codesandbox: [https://codesandbox.io/p/sandbox/optimistic-panna-dgh66c](https://codesandbox.io/p/sandbox/optimistic-panna-dgh66c), deployed version on Vercel: [https://clock-nextjs13.vercel.app/](https://clock-nextjs13.vercel.app/). This is not expected behaviour – I do not want to show my preloader again just because some of the dynamic metadata changed.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.1.0
      npm: 9.8.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.15
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

_No response_

<sub>[NEXT-1609](https://linear.app/vercel/issue/NEXT-1609/whole-page-component-re-renders-unmounts-when-route-changes)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
This ensures that the `.prefetch.rsc` requests respond with the correct `content-type` since this is used by Next.js to determine if a request is valid or not (and in the case it's invalid, an mpa navigation will occur)

Fixes: https://github.com/vercel/next.js/issues/54934

### CODE REVIEW

**Review by Ethan-Arrowood — APPROVED** [review]

File: packages/next/src/utils.ts [hunk 1]
```diff
@@ -48,6 +48,9 @@ export const MIB = 1024 * KIB;
 
 export const prettyBytes = (n: number) => bytes(n, { unitSeparator: ' ' });
 
+export const RSC_CONTENT_TYPE = 'x-component';
```
Comment (ijjk) [inline packages/next/src/utils.ts:51]: We should probably put this in the `routes-manifest` in Next.js and keep that as the source of truth in case we need to change it ever

**Review by ijjk — APPROVED** [review]
