### PR TITLE
Properly error on wrong token and handle team

### LINKED ISSUE #1072: Token authentication for rm appears to be broken
`rm` doesn't appear to be working for my CI with TravisCI

Log from [CI](https://travis-ci.org/spences10/blog.scottspence.me/jobs/328487903#L4622) 
Excerpt:
```sh
$ now run cleanup
> Error! No existing credentials found. Please run "now login" or pass "--token"
> More details: https://err.sh/now-cli/no-credentials-found
```

I have tried the following combinations:

`"cleanup": "now rm scottblog --safe --yes --token $NOW_TOKEN",`
`"cleanup": "now rm scottblog --safe --yes --token$NOW_TOKEN",`
`"cleanup": "now rm scottblog --safe --yes --token=$NOW_TOKEN",`

Removing some lines for brevity **`.travis.yaml`:**
```yaml
script:
  - npm i -g now@canary
  - npm run clean
  - npm run build
  - npm run deploy
after_script: 
  - if [ "$TRAVIS_BRANCH" = "development" ]; then npm run alias:dev; fi 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run alias:prod; fi
  - now run cleanup
```

My **`package.json`:**
```json
    "deploy": "now scottblog/ --token $NOW_TOKEN",
    "alias:dev": "now alias scottspence.now.sh --token $NOW_TOKEN",
    "alias:prod": "now alias blog.scottspence.me --token $NOW_TOKEN",
    "cleanup": "now rm scottblog --safe --yes --token=$NOW_TOKEN",
```

This seems similar to #804 but it is specifically the `rm` function, `alias` and `now` are working as expected.

Let me know if there is anything else you need  👍

### PR DESCRIPTION
**Pull request by leo**
This PR ensures we're not using the team from the config if `--token` was passed. In addition, a invalid token now leads to a proper error.

This closes #1072.

### CODE REVIEW

File: src/now.js [hunk 1]
```diff
@@ -437,10 +437,22 @@ const main = async (argv_) => {
...
+        token
+      })
+    } catch (err) {
+      console.error(error(err))
+      await exit(1)
+    }
+
+    // Don't use team from config if `--token` was set
+    if (ctx.config.sh && ctx.config.sh.currentTeam) {
+      delete ctx.config.sh.currentTeam
```
Comment (rauchg) [inline src/now.js:454]: Not a fan of changing the source of truth. I think that should be handled by the consumer of this function.

**Comment by timneutkens** [comment]
Thanks @leo sounds like exactly what I noticed earlier this week 👌
