### PR TITLE
[now-cli] Fix invalid token error message during project link

### LINKED ISSUE #3772: now dev requires login and is missing --token from help
`now dev` requires login now. If you don't log in it gives you a fun error like this:
```
Error! An unexpected error occurred!
  Error: The specified token is not valid
    at Object.getUser (/home/user/.config/yarn/global/node_modules/now/dist/index.js:2:2248948)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) Error: The specified token is not valid
    at Object.getUser (/home/user/.config/yarn/global/node_modules/now/dist/index.js:2:2248948)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

In CI you can specify a token using `-t` or `--token`, but this is not listed in the description shown by specifying `--help`.

### LINKED ISSUE #3786: Can't do anything after `now logout`
After logged out from cli, both login and logout don't work (now v17.0.3)

```
$ now logout
Now CLI 17.0.3
Error! The content of "~/.now/auth.json" is invalid. No `token` property found inside. Run `now login` to authorize.
$ now login
Now CLI 17.0.3
Error! An unexpected error occurred!
  Error: The specified token is not valid
```

I even can't see the help message
```
$ now --help
Now CLI 17.0.3
Error! An unexpected error occurred!
  Error: The specified token is not valid
```

### PR DESCRIPTION
**Pull request by styfle**
This PR improves the error message and prevents "An unexpected error occurred" when the token is invalid during a project link step.

I also added the `--token` option to `now dev --help` .

Lastly, I updated `now logout` to work correctly when the token is invalid.

- Fixes #3772 
- Fixes #3786

### CODE REVIEW

**Review by AndyBitz — APPROVED** [review]

**Review by TooTallNate — APPROVED** [review]

File: packages/now-cli/src/commands/dev/index.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ const help = () => {
     -h, --help             Output usage information
     -d, --debug            Debug mode [off]
     -l, --listen  [uri]    Specify a URI endpoint on which to listen [0.0.0.0:3000]
+    -t, --token   [token]  Specify an Authorization Token
```
Comment (lucleray) [inline packages/now-cli/src/commands/dev/index.ts:32]: 👀

Comment (lucleray) [reply packages/now-cli/src/commands/dev/index.ts:32]: Great catch 👍

**Review by lucleray — APPROVED** [review]
Thanks 🙏
