### PR TITLE
[now-build-utils] Fix static file serving from `now dev`

### LINKED ISSUE #3159: [now-dev] "Invalid `builds` property" when property not set
I get the following error when running `now dev` in a directory where there's a `build/` directory alongside the `now.json` file :

```bash
> Error! Invalid `builds` property:  should NOT have more than 128 items
```

I don't have any `builds` property defined in my `now.json` :

```json
{
  "version": 2,
  "name": "my-website",
  "routes": [
    { "src": "/catalogue",
      "dest": "index.html" },
    { "src": "/contactez-nous",
      "dest": "index.html" },
    { "src": "/qui-sommes-nous",
      "dest": "index.html" }
  ]
}
```

But the `build/` directory indeed contains more than 128 files, and `now dev` is confusing it with a `builds` property.

Unfortunately I can't change the name of this directory because it's automatically generated by [Stencil.js](https://github.com/ionic-team/stencil).

### PR DESCRIPTION
**Pull request by styfle**
This PR does a few things

- Separate tests into `integration.test.js` and `unit.test.js`
- Use one static build instead of many to avoid `should NOT have more than 128 items` error
- Add a new unit test so we don't regress

Fixes #3159

### CODE REVIEW

File: packages/now-build-utils/src/detect-builders.ts [hunk 1]
```diff
@@ -173,19 +173,17 @@ export async function detectBuilders(
...
-      );
+    } else if (
+      builders.length > 0 &&
+      files.some(f => !f.startsWith('api/') && f !== 'package.json')
+    ) {
+      // Everything besides the api directory
+      // and package.json can be served as static files
+      builders.push({
+        use: '@now/static',
+        src: '!api/**',
```
Comment (lucleray) [inline packages/now-build-utils/src/detect-builders.ts]: Won't `package.json` be served as a static file with this?

Comment (styfle) [reply packages/now-build-utils/src/detect-builders.ts]: No, theres a test for that and you can see the line above filters out package.json

Comment (lucleray) [reply packages/now-build-utils/src/detect-builders.ts]: > the line above filters out package.json

Isn't it just a condition and not a filter?

Comment (lucleray) [reply packages/now-build-utils/src/detect-builders.ts]: (and I couldn't find the test 😅)

Comment (TooTallNate) [reply packages/now-build-utils/src/detect-builders.ts]: Also perhaps based on the comment on line 181.

Comment (styfle) [reply packages/now-build-utils/src/detect-builders.ts]: Yes, I see now there is still a bug that the unit tests wont catch because they are not running the glob `src` string against the file inputs.

@TooTallNate It seems like I can't make a glob that negates two things. See this example: https://runkit.com/embed/ch57dy4bk27v

I would expect all to be false except the last one ^

Comment (styfle) [reply packages/now-build-utils/src/detect-builders.ts]: Ok, this has been fixed thanks to @lucleray 👍

**Review by TooTallNate — APPROVED** [review]
