### PR TITLE
[now-cli] Fix port assignment for `now dev`

### LINKED ISSUE #3761: Now dev uses start script instead of build script
Hey,
I have recently stumbled upon an issue where now dev runs the start script defined inside package.json (which is "react-scripts start" from CRA) instead of the build script. This causes to start the default CRA development server which prevents the actual start of now dev.
I'm not sure when this originally started happening (I'm pretty sure it's not more than 14 days), but I've observed similar behavior happening in all projects I've tried so far (including CRA and Next apps). It makes now dev unusable for me.
Screenshot 2020-02-06 at 18 00 05
Screenshot 2020-02-06 at 18 00 14
Screenshot 2020-02-06 at 19 30 40
I've already tried reinstalling the CLI but that unfortunately didn't seem to make any effect.
I've also tried reverting to the last commit that I was sure it was working, but that didn't help either, supporting my conclusion that this isn't a project related issue.
Is there any way I can make now dev command use the build script again?
(Started on cli version 16.7.3, current version 17.0.1).
I'd be thankful for any help. Thank you!

### PR DESCRIPTION
**Pull request by styfle**
This fixes a regression from #3749 where the PORT env var was removed. This is necessary so frameworks like create-react-app and gatsby can proxy to `now dev`.

Fixes #3761

### CODE REVIEW

**Review by AndyBitz — APPROVED** [review]

**Review by TooTallNate — APPROVED** [review]

File: packages/now-cli/src/util/dev/server.ts [hunk 1]
```diff
@@ -1646,15 +1648,12 @@ export default class DevServer {
       ...process.env,
       ...this.buildEnv,
       NOW_REGION: 'dev1',
+      PORT: `${port}`,
     };
 
-    const devCommand = this.devCommand
-      .replace(/\$PORT/g, `${port}`)
-      .replace(/%PORT%/g, `${port}`);
```
Comment (lucleray) [inline packages/now-cli/src/util/dev/server.ts:1653]: We need to keep these lines, because `$PORT` does not work on Windows.

Comment (styfle) [reply packages/now-cli/src/util/dev/server.ts:1653]: Thanks, I fixed it 🔧

**Review by lucleray — APPROVED** [review]
